Repository EVerest/everest-framework, pull requests merged in 2024-02, with the labels that each got.

#140 Name test target after repo to make it unique.
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: testing

#153 Remove duplicated line
  CMakeLists.txt
Labels: bug

#136 CI: Add cmake build and test
  .ci/build-kit/compile.sh
  .ci/build-kit/test.sh
  .github/workflows/cmake_build.yaml
Labels: CI/CD, testing
